---
# tasks file for ansible-role-flexera

- name: "Test Access to Beacon Server"
  ansible.builtin.uri:
    url: "{{ beacon_host }}"
    method: GET
    validate_certs: no
    status_code: [200, 400]
  when: beacon != false

- name: "Include tasks from assert playbook"
  ansible.builtin.include_tasks: assert.yaml

- name: "Include tasks from lookup playbook"
  ansible.builtin.include_tasks: lookup.yaml

- name: "Include tasks from install playbook"
  ansible.builtin.include_tasks: install.yaml
  when:
    - install is defined
    - install | bool

- name: "Include tasks from upgrade playbook"
  ansible.builtin.include_tasks: upgrade.yaml
  when:
    - upgrade is defined
    - upgrade | bool

- name: "Include tasks from cert playbook"
  ansible.builtin.include_tasks: cert.yaml
  when:
    - cert_replace is defined
    - cert_replace | bool
    - upgrade is not defined

- name: "Include tasks from sysv playbook"
  ansible.builtin.include_tasks: sysv.yaml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] >= '9'

- name: "Include tasks from config playbook"
  ansible.builtin.include_tasks: config.yaml
  when:
    - config_file is defined
